### ISSUE TITLE
Arranger collectionFS

### ISSUE THREAD

**Issue by GabrielDancause** [GabInc/blobon#625]
Exception in queued task: TypeError: Cannot read property 'start' of undefined

Voici le log :

I20150318-13:46:02.473(-4)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
I20150318-13:46:02.739(-4)? FileWorker ADDED - calling saveCopy images for hmA9tJbnsKiACb57a
I20150318-13:46:02.740(-4)? saving to store images
I20150318-13:46:02.740(-4)? createWriteStream images, internal: false
I20150318-13:46:02.741(-4)? createWriteStreamForFileKey images
I20150318-13:46:02.819(-4)? TempStore is mounted on storage.gridfs
I20150318-13:46:02.819(-4)? FS.TempStore creating read stream for hmA9tJbnsKiACb57a
I20150318-13:46:02.828(-4)? createReadStream _tempstore
I20150318-13:46:02.828(-4)? createReadStreamForFileKey _tempstore
I20150318-13:46:02.884(-4)? Exception in queued task: TypeError: Cannot read property 'start' of undefined
I20150318-13:46:02.884(-4)?     at Object.FS.StorageAdapter.createReadStream (packages/cfs:gridfs/gridfs.server.js:78:1)
I20150318-13:46:02.884(-4)?     at Object.self.adapter.createReadStreamForFileKey (packages/cfs:storage-adapter/storageAdapter.server.js:71:1)
I20150318-13:46:02.885(-4)?     at Object.self.adapter.createReadStream (packages/cfs:storage-adapter/storageAdapter.server.js:79:1)
I20150318-13:46:02.885(-4)?     at packages/cfs:tempstore/tempStore.js:363:1
I20150318-13:46:02.885(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150318-13:46:02.885(-4)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150318-13:46:02.885(-4)?     at CombinedStream._getNext (/Users/gab/.meteor/packages/cfs_tempstore/.0.0.2.gonsll++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:83:3)
I20150318-13:46:02.885(-4)?     at CombinedStream.resume (/Users/gab/.meteor/packages/cfs_tempstore/.0.0.2.gonsll++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:132:10)
I20150318-13:46:02.885(-4)?     at CombinedStream.pipe (/Users/gab/.meteor/packages/cfs_tempstore/.0.0.2.gonsll++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:64:8)
I20150318-13:46:02.886(-4)?     at saveCopy (packages/cfs:worker/fileWorker.js:181:1)
I20150318-13:46:02.913(-4)? FS.HTTP.unmount:
I20150318-13:46:02.918(-4)? {}
I20150318-13:46:02.918(-4)? Registered HTTP method URLs:
I20150318-13:46:02.918(-4)? /cfs/files/:collectionName/:id/:filename
I20150318-13:46:02.918(-4)? /cfs/files/:collectionName/:id
I20150318-13:46:02.918(-4)? /cfs/files/:collectionName

**Comment by GabrielDancause** [comment]
Reste a faire les forms pour : Artiste, CV_en, bio et bio_en
